#!/usr/bin/env node
/**
 * Phase 3 orchestrator: take a flow's output run directory, generate AI
 * captions for each step, and emit a captioned demo.mp4.
 *
 * Usage:
 *   npm run video                                # picks the most recent run
 *   npm run video -- output/<run-dir>            # explicit run directory
 *   npm run video -- --step-seconds 5            # override per-step duration
 *   npm run video -- --cover-seconds 4
 *
 * Env:
 *   ANTHROPIC_API_KEY — if set, captions are generated by Claude.
 *                       Otherwise, label-based fallback captions are used.
 *
 * Requires Pillow (pip install -r output/requirements.txt). FFmpeg is
 * located automatically — system `ffmpeg` is preferred, with a fallback
 * to the Playwright-bundled binary.
 */
import * as path from "path";
import { spawn } from "child_process";
import { logger } from "../utils/logger";
import { resolveRunDir, prepareRun } from "./captionRun";

interface CliFlags {
  runArg?: string;
  coverSeconds?: string;
  stepSeconds?: string;
  fps?: string;
  narrate?: boolean;
  voice?: string;
  coverNarration?: string;
}

async function main(): Promise<void> {
  const flags = parseArgs(process.argv.slice(2));
  const runDir = resolveRunDir(flags.runArg);
  if (!runDir) {
    logger.error("no run directory found in output/ — run a flow first or pass a path");
    process.exit(1);
  }

  await prepareRun(runDir);
  await runPython(runDir, flags);
}

function parseArgs(argv: string[]): CliFlags {
  const flags: CliFlags = {};
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--cover-seconds") flags.coverSeconds = argv[++i];
    else if (a === "--step-seconds") flags.stepSeconds = argv[++i];
    else if (a === "--fps") flags.fps = argv[++i];
    else if (a === "--narrate") flags.narrate = true;
    else if (a === "--voice") flags.voice = argv[++i];
    else if (a === "--cover-narration") flags.coverNarration = argv[++i];
    else if (a === "--latest") flags.runArg = a;
    else if (!a.startsWith("--")) flags.runArg = a;
  }
  return flags;
}

function runPython(runDir: string, flags: CliFlags): Promise<void> {
  return new Promise((resolve, reject) => {
    const script = path.resolve("output/videoGenerator.py");
    const args: string[] = [script, runDir];
    if (flags.coverSeconds) args.push("--cover-seconds", flags.coverSeconds);
    if (flags.stepSeconds) args.push("--step-seconds", flags.stepSeconds);
    if (flags.fps) args.push("--fps", flags.fps);
    if (flags.narrate) args.push("--narrate");
    if (flags.voice) args.push("--voice", flags.voice);
    if (flags.coverNarration) args.push("--cover-narration", flags.coverNarration);
    const child = spawn("python3", args, { stdio: "inherit" });
    child.on("error", (err) => reject(err));
    child.on("exit", (code) => {
      if (code === 0) {
        logger.info(`video written: ${path.join(runDir, "demo.mp4")}`);
        resolve();
      } else {
        reject(new Error(`videoGenerator.py exited with code ${code}`));
      }
    });
  });
}

main().catch((err) => {
  const msg = err instanceof Error ? (err.stack ?? err.message) : String(err);
  logger.error(msg);
  process.exit(1);
});
