#!/usr/bin/env node
/**
 * Phase 2 orchestrator: take a flow's output run directory, generate AI
 * captions for each step, and emit a PowerPoint deck.
 *
 * Usage:
 *   npm run pptx                          # picks the most recent output/<run>
 *   npm run pptx -- output/<run-dir>      # explicit run directory
 *   npm run pptx -- --latest              # alias for no-arg
 *
 * Env:
 *   ANTHROPIC_API_KEY — if set, captions are generated by Claude.
 *                       Otherwise, label-based fallback captions are used.
 */
import * as path from "path";
import { spawn } from "child_process";
import { logger } from "../utils/logger";
import { resolveRunDir, prepareRun } from "./captionRun";

async function main(): Promise<void> {
  const runDir = resolveRunDir(process.argv[2]);
  if (!runDir) {
    logger.error("no run directory found in output/ — run a flow first or pass a path");
    process.exit(1);
  }

  await prepareRun(runDir);
  await runPython(runDir);
}

function runPython(runDir: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const script = path.resolve("output/pptGenerator.py");
    const child = spawn("python3", [script, runDir], { stdio: "inherit" });
    child.on("error", (err) => reject(err));
    child.on("exit", (code) => {
      if (code === 0) {
        logger.info(`deck written: ${path.join(runDir, "demo.pptx")}`);
        resolve();
      } else {
        reject(new Error(`pptGenerator.py exited with code ${code}`));
      }
    });
  });
}

main().catch((err) => {
  const msg = err instanceof Error ? (err.stack ?? err.message) : String(err);
  logger.error(msg);
  process.exit(1);
});
