#!/usr/bin/env node
/**
 * Phase 2 orchestrator: take a flow's output run directory, generate AI
 * captions for each step, and emit a PowerPoint deck.
 *
 * Usage:
 *   npm run pptx                          # picks the most recent output/<run>
 *   npm run pptx -- output/<run-dir>      # explicit run directory
 *   npm run pptx -- --latest              # alias for no-arg
 *
 * Env:
 *   ANTHROPIC_API_KEY — if set, captions are generated by Claude.
 *                       Otherwise, label-based fallback captions are used.
 */
import * as fs from "fs/promises";
import { readdirSync, statSync, existsSync } from "fs";
import * as path from "path";
import { spawn } from "child_process";
import { logger } from "../utils/logger";
import { generateDescriptions, StepInput, SlideContent } from "./descriptionGenerator";

interface ManifestStep {
  index: number;
  label: string;
  action: string;
  selector?: string;
  value?: string;
  screenshot?: string;
  ok?: boolean;
}

interface Manifest {
  flow_name?: string;
  base_url?: string;
  generated_at?: string;
  total_steps?: number;
  executed_steps?: number;
  ok?: boolean;
  steps: ManifestStep[];
}

async function main(): Promise<void> {
  const arg = process.argv[2];
  const runDir =
    !arg || arg === "--latest" ? await pickLatestRun() : path.resolve(arg);
  if (!runDir) {
    logger.error("no run directory found in output/ — run a flow first or pass a path");
    process.exit(1);
    return;
  }

  const manifestPath = path.join(runDir, "steps.json");
  if (!existsSync(manifestPath)) {
    logger.error(`no steps.json in ${runDir}`);
    process.exit(1);
    return;
  }
  logger.info(`run dir: ${runDir}`);

  const manifest = JSON.parse(await fs.readFile(manifestPath, "utf-8")) as Manifest;
  const stepInputs: StepInput[] = manifest.steps.map((s) => ({
    index: s.index,
    label: s.label,
    action: s.action,
    selector: s.selector,
    value: s.value,
  }));

  logger.info(`generating captions for ${stepInputs.length} steps…`);
  const captions = await generateDescriptions(stepInputs);
  const captionByIndex = new Map<number, SlideContent>(captions.map((c) => [c.index, c]));

  const augmented: Manifest = {
    ...manifest,
    steps: manifest.steps.map((s) => {
      const caption = captionByIndex.get(s.index);
      return {
        ...s,
        title: caption?.title,
        description: caption?.description,
      } as ManifestStep & Partial<SlideContent>;
    }),
  };

  const augmentedPath = path.join(runDir, "steps_described.json");
  await fs.writeFile(augmentedPath, JSON.stringify(augmented, null, 2), "utf-8");
  logger.info(`wrote: ${augmentedPath}`);

  await runPython(runDir);
}

function pickLatestRun(): Promise<string | undefined> {
  const root = path.resolve("output");
  if (!existsSync(root)) return Promise.resolve(undefined);
  const entries = readdirSync(root)
    .map((name) => path.join(root, name))
    .filter((p) => {
      try {
        return statSync(p).isDirectory() && existsSync(path.join(p, "steps.json"));
      } catch {
        return false;
      }
    })
    .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
  return Promise.resolve(entries[0]);
}

function runPython(runDir: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const script = path.resolve("output/pptGenerator.py");
    const child = spawn("python3", [script, runDir], { stdio: "inherit" });
    child.on("error", (err) => reject(err));
    child.on("exit", (code) => {
      if (code === 0) {
        logger.info(`deck written: ${path.join(runDir, "demo.pptx")}`);
        resolve();
      } else {
        reject(new Error(`pptGenerator.py exited with code ${code}`));
      }
    });
  });
}

main().catch((err) => {
  const msg = err instanceof Error ? (err.stack ?? err.message) : String(err);
  logger.error(msg);
  process.exit(1);
});
